import { registry } from "@johnhenry/jth-runtime";
import { DYNAMIC_OP_DOCS } from "./op-docs.ts";
import { stdlibOpNames } from "./register.ts";

export const OPERATOR_REFERENCE_HEADER =
  "<!-- GENERATED by scripts/gen-operator-docs.ts from the jth-stdlib operator registry. Do not edit by hand. -->";

const esc = (s: string) => s.replace(/\|/g, "\\|");

/**
 * Render the operator reference (docs/operators.md) from the registry —
 * the single source of per-operator descriptions. Covers jth-stdlib's own
 * operators only, so the output does not depend on which other packages
 * happen to be loaded.
 */
export function operatorReferenceMarkdown(): string {
  const mine = new Set(stdlibOpNames());
  const rows = registry.infos().filter((i) => mine.has(i.name));
  const lines = [
    OPERATOR_REFERENCE_HEADER,
    "",
    "# Operator reference",
    "",
    "Arity is the number of stack items an operator consumes: a number, `variadic` (whole stack) or `varies` (depends on the stack or blocks).",
    "",
    "| Operator | Arity | Description |",
    "|----------|-------|-------------|",
    ...rows.map((i) => `| \`${esc(i.name)}\` | ${i.arity} | ${esc(i.description)} |`),
    "",
    "## Dynamic operators",
    "",
    "| Syntax | Arity | Description |",
    "|--------|-------|-------------|",
    ...Object.values(DYNAMIC_OP_DOCS).map(
      (d) => `| \`${esc(d.syntax)}\` | ${d.arity} | ${esc(d.description)} |`
    ),
    "",
  ];
  return lines.join("\n");
}
